/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author Menna
 */
public class proj2 extends javax.swing.JFrame {

    /**
     * Creates new form proj2
     */
    public proj2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formblue = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        hotel = new javax.swing.JButton();
        tourguide = new javax.swing.JButton();
        flight = new javax.swing.JButton();
        hotel1 = new javax.swing.JButton();
        formorange = new javax.swing.JPanel();
        mainmenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1075, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        formblue.setBackground(new java.awt.Color(44, 62, 80));
        formblue.setForeground(new java.awt.Color(44, 62, 80));

        back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(44, 62, 80));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        hotel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hotel.setForeground(new java.awt.Color(44, 62, 80));
        hotel.setText("Hotel Registeration");
        hotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelActionPerformed(evt);
            }
        });

        tourguide.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tourguide.setForeground(new java.awt.Color(44, 62, 80));
        tourguide.setText("Tour Guide");
        tourguide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tourguideActionPerformed(evt);
            }
        });

        flight.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        flight.setForeground(new java.awt.Color(44, 62, 80));
        flight.setText("Flight Registeration");
        flight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightActionPerformed(evt);
            }
        });

        hotel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hotel1.setForeground(new java.awt.Color(44, 62, 80));
        hotel1.setText("Archaeological landmarks");
        hotel1.setToolTipText("");
        hotel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formblueLayout = new javax.swing.GroupLayout(formblue);
        formblue.setLayout(formblueLayout);
        formblueLayout.setHorizontalGroup(
            formblueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formblueLayout.createSequentialGroup()
                .addGroup(formblueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formblueLayout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addComponent(flight, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formblueLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formblueLayout.createSequentialGroup()
                        .addGap(438, 438, 438)
                        .addComponent(tourguide, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formblueLayout.createSequentialGroup()
                        .addGap(403, 403, 403)
                        .addGroup(formblueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hotel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hotel, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(383, Short.MAX_VALUE))
        );
        formblueLayout.setVerticalGroup(
            formblueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formblueLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(flight, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(hotel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(hotel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tourguide, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        getContentPane().add(formblue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1070, 610));

        formorange.setBackground(new java.awt.Color(255, 153, 0));

        mainmenu.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        mainmenu.setForeground(new java.awt.Color(0, 0, 102));
        mainmenu.setText("        Main Menu");

        javax.swing.GroupLayout formorangeLayout = new javax.swing.GroupLayout(formorange);
        formorange.setLayout(formorangeLayout);
        formorangeLayout.setHorizontalGroup(
            formorangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainmenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
        );
        formorangeLayout.setVerticalGroup(
            formorangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formorangeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainmenu, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
        );

        getContentPane().add(formorange, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 100));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void flightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightActionPerformed
        // TODO add your handling code here:
        flight_registration flight_registrationObj = new flight_registration();
        flight_registrationObj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_flightActionPerformed

    private void tourguideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tourguideActionPerformed
        // TODO add your handling code here:
        avilable_tourguide obj = new avilable_tourguide();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tourguideActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        setVisible(false);
         selection proj = new selection();
         proj.setVisible(true);
        
        
    }//GEN-LAST:event_backActionPerformed

    private void hotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelActionPerformed
        // TODO add your handling code here:
        countries1 obj = new countries1();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_hotelActionPerformed

    private void hotel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotel1ActionPerformed
        // TODO add your handling code here:
        countries22 obj = new countries22();
        obj.setVisible (true);
        this.setVisible(false);
    }//GEN-LAST:event_hotel1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(proj2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(proj2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(proj2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(proj2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new proj2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton flight;
    private javax.swing.JPanel formblue;
    private javax.swing.JPanel formorange;
    private javax.swing.JButton hotel;
    private javax.swing.JButton hotel1;
    private javax.swing.JLabel mainmenu;
    private javax.swing.JButton tourguide;
    // End of variables declaration//GEN-END:variables

    private void close() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
