/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.io.*;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Menna
 */
public class userrsearch extends javax.swing.JFrame {

    /**
     * Creates new form userrsearch
     */
    public userrsearch() {
        initComponents();
        happy.setVisible(false);
        sad.setVisible(false);
        success.setVisible(false);
        fail.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        confirm = new javax.swing.JButton();
        back = new javax.swing.JButton();
        happy = new javax.swing.JLabel();
        sad = new javax.swing.JLabel();
        success = new javax.swing.JLabel();
        fail = new javax.swing.JLabel();
        blueform = new javax.swing.JPanel();
        orangeform = new javax.swing.JPanel();
        search = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1075, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Your ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 190, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 185, 290, 40));

        confirm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        confirm.setForeground(new java.awt.Color(44, 62, 80));
        confirm.setText("Confirm");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        getContentPane().add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 187, -1, -1));

        back.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        back.setForeground(new java.awt.Color(44, 62, 80));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, 120, -1));

        happy.setIcon(new javax.swing.ImageIcon("C:\\Users\\smohamed\\Documents\\NetBeansProjects\\part 1\\src\\happy.png")); // NOI18N
        getContentPane().add(happy, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 280, 378, 340));

        sad.setIcon(new javax.swing.ImageIcon("C:\\Users\\smohamed\\Documents\\NetBeansProjects\\part 1\\src\\sad.png")); // NOI18N
        getContentPane().add(sad, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 334, -1, -1));

        success.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        success.setForeground(new java.awt.Color(255, 255, 255));
        success.setText("Your flight is booked successfully");
        getContentPane().add(success, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 372, -1, -1));

        fail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fail.setForeground(new java.awt.Color(255, 255, 255));
        fail.setText("Sorry, The ID is wrong");
        getContentPane().add(fail, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 303, -1, -1));

        blueform.setBackground(new java.awt.Color(44, 62, 80));
        blueform.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout blueformLayout = new javax.swing.GroupLayout(blueform);
        blueform.setLayout(blueformLayout);
        blueformLayout.setHorizontalGroup(
            blueformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        blueformLayout.setVerticalGroup(
            blueformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(blueform, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1080, 600));

        orangeform.setBackground(new java.awt.Color(255, 153, 0));

        search.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        search.setForeground(new java.awt.Color(0, 0, 102));
        search.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search.setText("Confirm");

        javax.swing.GroupLayout orangeformLayout = new javax.swing.GroupLayout(orangeform);
        orangeform.setLayout(orangeformLayout);
        orangeformLayout.setHorizontalGroup(
            orangeformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orangeformLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(815, Short.MAX_VALUE))
        );
        orangeformLayout.setVerticalGroup(
            orangeformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orangeformLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(orangeform, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
String str = jTextField1.getText();
Scanner f1;
String line = "";
int counter=0;
        try {
            
             f1 = new Scanner(new File("C:\\Users\\smohamed\\Documents\\NetBeansProjects\\part 1\\src\\flightDetails.txt"));    

            while(f1.hasNextLine())
            {
                
            line= f1.nextLine();
            
            if(line.startsWith(str))
            {
               counter++;
            break;
            }
            }
        f1.close();
        
            if(counter !=0)
            {
           happy.setVisible(true);
        sad.setVisible(false);
        success.setVisible(true);
        fail.setVisible(false);
        jTextField1.setText(" ");
       } 
            else{
             happy.setVisible(false);
        sad.setVisible(true);
        success.setVisible(false);
        fail.setVisible(true);
        jTextField1.setText(" ");
            }  
            f1.close();}
            catch (FileNotFoundException ex) {
            Logger.getLogger(userrsearch.class.getName()).log(Level.SEVERE, null, ex);}
        


        
    }//GEN-LAST:event_confirmActionPerformed

    
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
       flight_registration sh = new flight_registration();
        sh.setVisible(true);
        this.setVisible(false);
        //adminn proj = new adminn();
       // proj.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userrsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userrsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userrsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userrsearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userrsearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JPanel blueform;
    private javax.swing.JButton confirm;
    private javax.swing.JLabel fail;
    private javax.swing.JLabel happy;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel orangeform;
    private javax.swing.JLabel sad;
    private javax.swing.JLabel search;
    private javax.swing.JLabel success;
    // End of variables declaration//GEN-END:variables
}
